# https://taskfile.dev

version: '3'

vars:
  BINARY_NAME: zflow
  MAIN_PATH: ./app/zflow/cmd/main.go

tasks:
  default:
    desc: 显示帮助信息
    cmds:
      - task --list

  proto-registry:
    desc: 生成 protobuf 文件
    cmds:
      - protoc --go_out=. --go_opt=paths=source_relative --go-grpc_out=. --go-grpc_opt=paths=source_relative api/registry/registry.proto
    silent: true

  run-zflow:
    desc: 运行应用程序
    cmds:
      - go run {{.MAIN_PATH}}
    silent: true

  

