// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: api/base/base.proto

package base

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BaseService_GetNodeTypes_FullMethodName = "/base.BaseService/GetNodeTypes"
	BaseService_GetConnTypes_FullMethodName = "/base.BaseService/GetConnTypes"
	BaseService_RunNode_FullMethodName      = "/base.BaseService/RunNode"
)

// BaseServiceClient is the client API for BaseService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 节点类型服务
type BaseServiceClient interface {
	// 获取所有可用的节点类型
	GetNodeTypes(ctx context.Context, in *GetNodeTypesRequest, opts ...grpc.CallOption) (*GetNodeTypesResponse, error)
	// 获取所有可用的连接类型
	GetConnTypes(ctx context.Context, in *GetConnTypesRequest, opts ...grpc.CallOption) (*GetConnTypesResponse, error)
	// 运行指定节点
	RunNode(ctx context.Context, in *RunNodeRequest, opts ...grpc.CallOption) (*RunNodeResponse, error)
}

type baseServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBaseServiceClient(cc grpc.ClientConnInterface) BaseServiceClient {
	return &baseServiceClient{cc}
}

func (c *baseServiceClient) GetNodeTypes(ctx context.Context, in *GetNodeTypesRequest, opts ...grpc.CallOption) (*GetNodeTypesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNodeTypesResponse)
	err := c.cc.Invoke(ctx, BaseService_GetNodeTypes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *baseServiceClient) GetConnTypes(ctx context.Context, in *GetConnTypesRequest, opts ...grpc.CallOption) (*GetConnTypesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetConnTypesResponse)
	err := c.cc.Invoke(ctx, BaseService_GetConnTypes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *baseServiceClient) RunNode(ctx context.Context, in *RunNodeRequest, opts ...grpc.CallOption) (*RunNodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RunNodeResponse)
	err := c.cc.Invoke(ctx, BaseService_RunNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BaseServiceServer is the server API for BaseService service.
// All implementations must embed UnimplementedBaseServiceServer
// for forward compatibility.
//
// 节点类型服务
type BaseServiceServer interface {
	// 获取所有可用的节点类型
	GetNodeTypes(context.Context, *GetNodeTypesRequest) (*GetNodeTypesResponse, error)
	// 获取所有可用的连接类型
	GetConnTypes(context.Context, *GetConnTypesRequest) (*GetConnTypesResponse, error)
	// 运行指定节点
	RunNode(context.Context, *RunNodeRequest) (*RunNodeResponse, error)
	mustEmbedUnimplementedBaseServiceServer()
}

// UnimplementedBaseServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBaseServiceServer struct{}

func (UnimplementedBaseServiceServer) GetNodeTypes(context.Context, *GetNodeTypesRequest) (*GetNodeTypesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNodeTypes not implemented")
}
func (UnimplementedBaseServiceServer) GetConnTypes(context.Context, *GetConnTypesRequest) (*GetConnTypesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetConnTypes not implemented")
}
func (UnimplementedBaseServiceServer) RunNode(context.Context, *RunNodeRequest) (*RunNodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RunNode not implemented")
}
func (UnimplementedBaseServiceServer) mustEmbedUnimplementedBaseServiceServer() {}
func (UnimplementedBaseServiceServer) testEmbeddedByValue()                     {}

// UnsafeBaseServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BaseServiceServer will
// result in compilation errors.
type UnsafeBaseServiceServer interface {
	mustEmbedUnimplementedBaseServiceServer()
}

func RegisterBaseServiceServer(s grpc.ServiceRegistrar, srv BaseServiceServer) {
	// If the following call pancis, it indicates UnimplementedBaseServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BaseService_ServiceDesc, srv)
}

func _BaseService_GetNodeTypes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNodeTypesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseServiceServer).GetNodeTypes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BaseService_GetNodeTypes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseServiceServer).GetNodeTypes(ctx, req.(*GetNodeTypesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BaseService_GetConnTypes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConnTypesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseServiceServer).GetConnTypes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BaseService_GetConnTypes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseServiceServer).GetConnTypes(ctx, req.(*GetConnTypesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BaseService_RunNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseServiceServer).RunNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BaseService_RunNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseServiceServer).RunNode(ctx, req.(*RunNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BaseService_ServiceDesc is the grpc.ServiceDesc for BaseService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BaseService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "base.BaseService",
	HandlerType: (*BaseServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetNodeTypes",
			Handler:    _BaseService_GetNodeTypes_Handler,
		},
		{
			MethodName: "GetConnTypes",
			Handler:    _BaseService_GetConnTypes_Handler,
		},
		{
			MethodName: "RunNode",
			Handler:    _BaseService_RunNode_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/base/base.proto",
}
